#!/usr/bin/env node

/**
 * KodeKit Project Cleanup Script
 *
 * This script removes unnecessary files and directories from the Next.js migration
 * and updates .gitignore to prevent future clutter.
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// ANSI color codes
const colors = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  red: "\x1b[31m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  magenta: "\x1b[35m",
};

class ProjectCleaner {
  constructor() {
    this.deletedFiles = [];
    this.deletedDirs = [];
    this.errors = [];
    this.dryRun = process.argv.includes("--dry-run");
  }

  log(message, type = "info") {
    const colorMap = {
      info: colors.blue,
      success: colors.green,
      warning: colors.yellow,
      error: colors.red,
      header: colors.magenta,
    };

    console.log(`${colorMap[type]}${message}${colors.reset}`);
  }

  // Files and directories to remove
  getFilesToRemove() {
    return [
      // Legacy Vite files
      "src",
      "src-vite",
      "my-nextjs-app",
      "dev-dist",
      "index.html",

      // Backup files
      "package-vite-backup.json",
      "package-nextjs.json",
      "tsconfig-vite-backup.json",
      "tsconfig-nextjs.json",
      "postcss-vite-backup.js",
      "postcss.config-nextjs.js",
      "tailwind-vite-backup.js",
      "tailwind.config-nextjs.js",
      "eslint-vite-backup.js",
      "eslint.config-nextjs.js",

      // Migration files
      "migrate-to-nextjs.sh",
      "migrate-to-nextjs.bat",
      "verify-nextjs-setup.cjs",
      "NEXTJS_MIGRATION_TASK_1_COMPLETE.md",
      "YARN_UPDATE_SUMMARY.md",
      "TASK_3_IMPLEMENTATION_SUMMARY.md",
      "PERFORMANCE_OPTIMIZATION_SUMMARY.md",
      "SEOUTILS_IMPLEMENTATION_GUIDE.md",
      "GOOGLE_INDEXING_FIX.md",

      // Duplicate configs
      "tsconfig.app.json",
      "tsconfig.node.json",
      "tsconfig.tsbuildinfo",

      // Build files (if they exist in root)
      "robots.txt", // We have app/robots.ts

      // Test directories
      "app/test",
      "app/test-tool",
      "components/IntegrationTest.tsx",

      // Yarn lock if using npm
      "yarn.lock",
    ];
  }

  // Check if file/directory exists
  exists(filePath) {
    try {
      return fs.existsSync(path.join(process.cwd(), filePath));
    } catch (error) {
      return false;
    }
  }

  // Remove file or directory
  removeItem(itemPath) {
    const fullPath = path.join(process.cwd(), itemPath);

    try {
      if (!this.exists(itemPath)) {
        return false; // Item doesn't exist
      }

      if (this.dryRun) {
        this.log(`[DRY RUN] Would remove: ${itemPath}`, "warning");
        return true;
      }

      const stats = fs.statSync(fullPath);

      if (stats.isDirectory()) {
        fs.rmSync(fullPath, { recursive: true, force: true });
        this.deletedDirs.push(itemPath);
        this.log(`✅ Removed directory: ${itemPath}`, "success");
      } else {
        fs.unlinkSync(fullPath);
        this.deletedFiles.push(itemPath);
        this.log(`✅ Removed file: ${itemPath}`, "success");
      }

      return true;
    } catch (error) {
      this.errors.push({ item: itemPath, error: error.message });
      this.log(`❌ Failed to remove ${itemPath}: ${error.message}`, "error");
      return false;
    }
  }

  // Update .gitignore file
  updateGitignore() {
    const gitignorePath = path.join(process.cwd(), ".gitignore");

    const newGitignoreContent = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
/coverage

# Next.js
/.next/
/out/

# Production
/build
/dist
/dist-ssr

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage
.grunt

# Bower dependency directory
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# parcel-bundler cache
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
public

# Vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

# IDE
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# OS
Thumbs.db
.DS_Store

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Temporary files
*.tmp
*.temp

# Build artifacts
/public/sw.js
/public/workbox-*.js
/public/fallback-*.js

# Backup files
*-backup.*
*.backup
*-vite-backup.*
*-nextjs.*

# Migration files
migrate-to-nextjs.*
verify-nextjs-setup.*
*MIGRATION*
*SUMMARY*
*GUIDE*

# Test directories
/app/test/
/app/test-tool/

# Cleanup files
cleanup-plan.md
`;

    try {
      if (this.dryRun) {
        this.log("[DRY RUN] Would update .gitignore", "warning");
        return;
      }

      fs.writeFileSync(gitignorePath, newGitignoreContent);
      this.log("✅ Updated .gitignore", "success");
    } catch (error) {
      this.errors.push({ item: ".gitignore", error: error.message });
      this.log(`❌ Failed to update .gitignore: ${error.message}`, "error");
    }
  }

  // Clean up package.json scripts
  cleanPackageJson() {
    const packagePath = path.join(process.cwd(), "package.json");

    try {
      const packageJson = JSON.parse(fs.readFileSync(packagePath, "utf8"));

      // Remove Vite-related scripts
      const scriptsToRemove = [
        "dev:vite",
        "build:vite",
        "preview:vite",
        "migrate",
        "verify-setup",
      ];

      let modified = false;
      scriptsToRemove.forEach((script) => {
        if (packageJson.scripts && packageJson.scripts[script]) {
          delete packageJson.scripts[script];
          modified = true;
        }
      });

      if (modified && !this.dryRun) {
        fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
        this.log("✅ Cleaned up package.json scripts", "success");
      } else if (modified && this.dryRun) {
        this.log("[DRY RUN] Would clean up package.json scripts", "warning");
      }
    } catch (error) {
      this.errors.push({ item: "package.json", error: error.message });
      this.log(`❌ Failed to clean package.json: ${error.message}`, "error");
    }
  }

  // Generate cleanup report
  generateReport() {
    this.log("\n" + "=".repeat(60), "header");
    this.log("PROJECT CLEANUP REPORT", "header");
    this.log("=".repeat(60), "header");

    this.log(`\nSUMMARY:`, "header");
    this.log(`📁 Directories removed: ${this.deletedDirs.length}`, "info");
    this.log(`📄 Files removed: ${this.deletedFiles.length}`, "info");
    this.log(
      `❌ Errors: ${this.errors.length}`,
      this.errors.length > 0 ? "error" : "success"
    );

    if (this.deletedDirs.length > 0) {
      this.log(`\nDIRECTORIES REMOVED:`, "header");
      this.deletedDirs.forEach((dir) => this.log(`  - ${dir}`, "success"));
    }

    if (this.deletedFiles.length > 0) {
      this.log(`\nFILES REMOVED:`, "header");
      this.deletedFiles.forEach((file) => this.log(`  - ${file}`, "success"));
    }

    if (this.errors.length > 0) {
      this.log(`\nERRORS:`, "header");
      this.errors.forEach((error) =>
        this.log(`  - ${error.item}: ${error.error}`, "error")
      );
    }

    this.log(`\nRECOMMENDATIONS:`, "header");
    this.log('1. Run "npm run build" to verify everything still works', "info");
    this.log("2. Test key functionality to ensure nothing is broken", "info");
    this.log("3. Commit changes to git", "info");
    this.log("4. Update team members about the cleanup", "info");

    if (this.dryRun) {
      this.log(
        `\nTo execute the cleanup, run: node scripts/cleanup-project.js`,
        "warning"
      );
    }
  }

  // Main cleanup function
  async cleanup() {
    this.log("Starting KodeKit Project Cleanup...", "header");

    if (this.dryRun) {
      this.log("🔍 DRY RUN MODE - No files will be deleted", "warning");
    }

    // Get files to remove
    const filesToRemove = this.getFilesToRemove();

    this.log(`\nProcessing ${filesToRemove.length} items...`, "info");

    // Remove each file/directory
    for (const item of filesToRemove) {
      this.removeItem(item);
    }

    // Update .gitignore
    this.log("\nUpdating .gitignore...", "info");
    this.updateGitignore();

    // Clean package.json
    this.log("\nCleaning package.json...", "info");
    this.cleanPackageJson();

    // Generate report
    this.generateReport();

    return this.errors.length === 0;
  }
}

// Run cleanup if this script is executed directly
if (require.main === module) {
  const cleaner = new ProjectCleaner();

  cleaner
    .cleanup()
    .then((success) => {
      process.exit(success ? 0 : 1);
    })
    .catch((error) => {
      console.error("Cleanup failed:", error);
      process.exit(1);
    });
}

module.exports = ProjectCleaner;
